version: "3.6"

services:
  splash:
    image: scrapinghub/splash:3.2

  detectem: &detectem
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SETUP_SPLASH=False
      - SPLASH_URL=http://splash:8050
    entrypoint:
      - python
      - detectem/cli.py
    volumes:
      - ./detectem:/detectem

  tests:
    <<: *detectem
    entrypoint:
      - pytest
      - tests
